include_directories(${PROJECT_SOURCE_DIR}/src)

add_executable(unit_test_base unit_test_base.cc)
add_executable(unit_test_scalar unit_test_scalar.cc)
add_executable(unit_test_span unit_test_span.cc)
add_executable(unit_test_view unit_test_view.cc)
add_executable(unit_test_stl unit_test_stl.cc)
add_executable(unit_test_math unit_test_math.cc)
add_executable(unit_test_layout unit_test_layout.cc)
add_executable(unit_test_index unit_test_index.cc)
add_executable(unit_test_simd_int unit_test_simd_int.cc)
add_executable(unit_test_simd_float unit_test_simd_float.cc)
add_executable(unit_test_simd_double unit_test_simd_double.cc)
add_executable(unit_test_expr unit_test_expr.cc)
add_executable(unit_test_unary unit_test_unary.cc)
add_executable(unit_test_condition unit_test_condition.cc)

add_mingw_link(unit_test_base)
add_mingw_link(unit_test_scalar)
add_mingw_link(unit_test_span)
add_mingw_link(unit_test_view)
add_mingw_link(unit_test_stl)
add_mingw_link(unit_test_math)
add_mingw_link(unit_test_layout)
add_mingw_link(unit_test_index)
add_mingw_link(unit_test_simd_int)
add_mingw_link(unit_test_simd_float)
add_mingw_link(unit_test_simd_double)
add_mingw_link(unit_test_expr)
add_mingw_link(unit_test_unary)
add_mingw_link(unit_test_condition)
